version: "2.2"

# Containers networking configuration
networks:
  game.io:
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16
          gateway: 172.26.0.1

services:
  # Nodejs service 1 -- the first service will build the image for the others
  game-server:
    image: game.io-image:v1
    build: .
    volumes:
      - .:/app
    command: node src/index
    networks:
      game.io:
        ipv4_address: 172.26.0.2
  player1:
    image: game.io-image:v1
    volumes:
      - .:/app
    command: node player/index
    networks:
      game.io:
        ipv4_address: 172.26.0.3
  player2:
    image: game.io-image:v1
    volumes:
      - .:/app
    command: node player/index
    networks:
      game.io:
        ipv4_address: 172.26.0.4
